name: wp
recipe: wordpress
services:
  appserver: 
    type: php
    webroot: app
    config:
      ssl: true
      database: 'mysql:8.0'
      via: 'nginx:1.24'
      xdebug: true
      cache: redis
      composer_version: 2
      config:
        php: config/php.ini
        phpmyadmin: config/phpmyadmin.ini
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - npm install
      - npm install gulp-cli -g
      - npm install yarn -g
      - composer install
    globals: 
      gulp-cli: latest
      yarn: latest
  cache:
    type: redis
    persist: true
  database:
    portforward: true
  mail:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  redis-cli:
    service: cache
  node:
    service: appserver
  npm:
    service: appserver
  gulp:
    service: appserver
  yarn:
    service: appserver
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
proxy:
  appserver:
    - wp.lndo.site
    - '*.wp.lndo.site'
  mail:
    - mail.lndo.site
  phpmyadmin:
    - pma.lndo.site
