name: wp
recipe: wordpress
config:
  webroot: app
  ssl: true
  php: '8.2'
  via: nginx:1.24
  database: mysql:8.0 # Mariadb or mysql
  config:
    vhosts: 'config/default.conf'
    php: 'config/php.ini'
    phpmyadmin: 'config/phpmyadmin.ini'
services:
  database:
    type: mysql:8.0
    creds: 
      user: root
      password: mysql
      database: wordpress
    run:
      - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';FLUSH PRIVILEGES;"
  node:
    type: node:18
    command: npm start
    build: 
      - npm install
      - gulp
      - yarn
#     - bower
    globals:
      gulp-cli: latest
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  node: 
    service: node
  npm:
    service: node
  gulp:
    service: node
  yarn:
    service: node
#  bower:
#   service: node
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
proxy:
  # Appserver_nginx or appserver for apache
  appserver_nginx:  
    - wp.lndo.site
    - "*.wp.lndo.site"
  mailhog:
    - mail.wp.lndo.site
  phpmyadmin:
    - pma.wp.lndo.site
# Add following options to your Browsersync script:
# "browserSyncOptions": {
#     "proxy": "https://wp.lndo.site",
#     "port": 80,
#     "SSL": true,
#     "open": false,
#     "notify": false
# }
